# Generated by Django 4.0.3 on 2022-06-13 06:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='This field is autogenerated', max_length=100, null=True, unique=True)),
                ('address_line', models.CharField(max_length=150)),
                ('active_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='WaterBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('units', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=145.0, max_digits=9, verbose_name='Unit Price (KES)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('month', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=47, null=True)),
                ('meter_rent', models.DecimalField(decimal_places=2, default=100, max_digits=9)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cleared', models.BooleanField(default=False)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.customer')),
            ],
            options={
                'verbose_name_plural': 'Water Billing Cycles',
            },
        ),
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('meter_number', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('custom_er', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=9)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=9)),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('reading_added', models.DateField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.waterbilling')),
            ],
        ),
        migrations.AddField(
            model_name='waterbilling',
            name='meter_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.watermeter'),
        ),
        migrations.AddField(
            model_name='customer',
            name='metre_number',
            field=models.OneToOneField(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customers', to='clients.watermeter'),
        ),
    ]
