# Generated by Django 4.0.3 on 2022-06-13 06:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('payment_code', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_method', models.CharField(help_text='e.g. MPESA, KCB ...', max_length=30)),
                ('date_paid', models.DateField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('remarks', models.TextField(blank=True, max_length=155, null=True, verbose_name='Message?')),
                ('lock', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.waterbilling')),
            ],
            options={
                'verbose_name': 'Billing 2 | Water Billing Payments',
                'verbose_name_plural': 'Billing 2 | Water Billing Payments',
            },
        ),
    ]
